Repository zesty-io/manager-ui, pull requests merged in 2023-08, with the labels that each got.

#2191 Content API Tab
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemNavigation/ItemNavigation.js
  src/apps/schema/src/app/components/ModelApi/ApiCardList.tsx
  src/apps/schema/src/app/components/ModelApi/ApiDetails.tsx
  src/apps/schema/src/app/components/ModelApi/ApiDomainEndpoints.tsx
  src/apps/schema/src/app/components/ModelApi/index.tsx
Labels: ready, vqa

#2208 Auto-select newly uploaded files when in content editor
  src/apps/media/src/app/components/Header.tsx
Labels: ready, vqa

#2213 Highlight recently created folders
  src/apps/media/src/app/components/Folder/index.tsx
  src/apps/media/src/app/components/MediaGrid.tsx
  src/apps/media/src/app/components/NewFolderDialog.tsx
  src/shell/services/mediaManager.ts
Labels: ready, vqa

#2215 Focus done button after file selection and add spacing to Selected text
  src/apps/media/src/app/components/DnDProvider.tsx
  src/apps/media/src/app/components/Header.tsx
Labels: ready, vqa

#2214 Fix all media not in a selected state when in insert media modal
  src/apps/media/src/app/components/Sidebar/Menu.tsx
Labels: ready

#2205 Add proper permission limitations to Item Versioning
  cypress/e2e/search/advanced-search.spec.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ItemVersioning.js
Labels: ready

#2207 Remove analytics app
  src/apps/reports/src/app/ReportingApp.js
  src/apps/reports/src/app/components/ReportingNav.js
  src/apps/reports/src/app/views/Analytics/Analytics.less
  src/apps/reports/src/app/views/Analytics/components/ContentVelocity/ContentVelocity.js
  src/apps/reports/src/app/views/Analytics/components/ContentVelocity/ContentVelocity.less
  src/apps/reports/src/app/views/Analytics/components/ContentVelocity/index.js
  src/apps/reports/src/app/views/Analytics/components/GoogleAuthOverlay/GaAuthenticate.js
  src/apps/reports/src/app/views/Analytics/components/GoogleAuthOverlay/GoogleAuthOverlay.js
  src/apps/reports/src/app/views/Analytics/components/GoogleAuthOverlay/GoogleAuthOverlay.less
  src/apps/reports/src/app/views/Analytics/components/GoogleAuthOverlay/index.js
  src/apps/reports/src/app/views/Analytics/components/InboundTraffic/InboundTraffic.js
  src/apps/reports/src/app/views/Analytics/components/InboundTraffic/InboundTraffic.less
  src/apps/reports/src/app/views/Analytics/components/InboundTraffic/index.js
  src/apps/reports/src/app/views/Analytics/components/PageviewTraffic/PageviewTraffic.js
  src/apps/reports/src/app/views/Analytics/components/PageviewTraffic/PageviewTraffic.less
  src/apps/reports/src/app/views/Analytics/components/PageviewTraffic/index.js
  src/apps/reports/src/app/views/Analytics/components/RecentlyEdited/RecentlyEdited.js
  src/apps/reports/src/app/views/Analytics/components/RecentlyEdited/RecentlyEdited.less
  src/apps/reports/src/app/views/Analytics/components/RecentlyEdited/index.js
  src/apps/reports/src/app/views/Analytics/components/SocialTraffic/SocialTraffic.js
  src/apps/reports/src/app/views/Analytics/components/SocialTraffic/SocialTraffic.less
  src/apps/reports/src/app/views/Analytics/components/SocialTraffic/index.js
  src/apps/reports/src/app/views/Analytics/components/TopPerforming/TopPerforming.js
  src/apps/reports/src/app/views/Analytics/components/TopPerforming/index.js
  src/apps/reports/src/app/views/Analytics/index.js
  src/apps/reports/src/app/views/Analytics/shelldata.js
  src/shell/components/GlobalDocsMenu/config.ts
  src/shell/components/GlobalHelpMenu/GlobalHelpMenu.js
  src/shell/components/InstanceFlyoutMenuModal/DocsMenu.tsx
  src/shell/components/InviteMembersModal/RoleAccessInfo.tsx
  src/shell/store/ui.ts
Labels: ready

#2197 Feature: Content app sidebar redesign
  cypress/e2e/content/navigation.spec.js
  package-lock.json
  package.json
  public/images/notFoundTransparent.png
  src/apps/content-editor/src/app/ContentEditor.js
  src/apps/content-editor/src/app/ContentEditor.less
  src/apps/content-editor/src/app/components/ContentNav/NavError.tsx
  src/apps/content-editor/src/app/components/ContentNav/index.tsx
  src/apps/content-editor/src/app/components/HideContentItemDialog.tsx
  src/apps/content-editor/src/app/components/Nav/ContentNav.js
  src/apps/content-editor/src/app/components/Nav/ContentNav.less
  src/apps/content-editor/src/app/components/Nav/ItemsFilter.js
  src/apps/content-editor/src/app/components/Nav/components/ContentNavToggle/ContentNavToggle.js
  src/apps/content-editor/src/app/components/Nav/components/ContentNavToggle/index.js
  src/apps/content-editor/src/app/components/Nav/index.js
  src/apps/content-editor/src/app/components/ReorderNav/DragComponents/DragList.js
  src/apps/content-editor/src/app/components/ReorderNav/DragComponents/styles.less
  src/apps/content-editor/src/app/components/ReorderNav/ReorderNav.js
  src/apps/content-editor/src/app/views/LinkCreate/LinkCreate.js
  src/apps/content-editor/src/app/views/LinkEdit/LinkEdit.js
  src/apps/content-editor/src/store/navContent.js
  src/apps/home/app/index.tsx
  src/apps/release/src/app/ReleaseApp.js
  src/apps/release/src/app/views/Activate/Activate.js
  src/apps/release/src/app/views/CreateRelease/CreateRelease.js
  src/apps/release/src/app/views/ListReleases/ListReleases.js
  src/apps/release/src/app/views/ListReleases/Release.js
  src/apps/release/src/app/views/ViewRelease/ViewRelease.js
  src/apps/release/src/app/views/ViewRelease/components/Header/Header.js
  src/apps/release/src/app/views/ViewRelease/components/Header/components/DeleteRelease/DeleteRelease.js
  src/mui.d.ts
  src/shell/components/AppSidebar/index.tsx
  src/shell/components/CreateContentItemDialog.tsx
  src/shell/components/NavTree/components/NavTreeItem.tsx
  src/shell/components/NavTree/index.tsx
  src/shell/components/ResizeableContainer.tsx
  src/shell/components/global-menu/index.tsx
  src/shell/components/global-sidebar/GlobalSidebar.tsx
  src/shell/components/global-sidebar/components/InstanceAvatar.tsx
  src/shell/components/global-sidebar/components/InstanceMenu/index.tsx
  src/shell/services/accounts.ts
  src/shell/services/instance.ts
  src/shell/services/types.ts
  src/shell/store/content.js
  src/shell/views/Shell/Shell.tsx
Labels: ready, vqa

#2235 Fix: Unable to re-order child tree
  src/apps/content-editor/src/app/components/ReorderNav/DragComponents/styles.less
Labels: ready

#2225 Feat: App sidebar redesigns
  cypress/e2e/media/contentmodal.spec.js
  cypress/e2e/media/folders.spec.js
  public/images/googleAnalyticsLogo.png
  public/images/googleChromeLogo.png
  public/images/microsoftLogo.png
  public/images/nodejsLogo.png
  public/images/npmLogo.png
  public/images/zestyRocket.svg
  src/apps/content-editor/src/app/components/ContentNav/index.tsx
  src/apps/home/app/components/Header.tsx
  src/apps/marketplace/src/app/components/InstallApp.tsx
  src/apps/marketplace/src/app/components/Sidebar.tsx
  src/apps/marketplace/src/app/index.tsx
  src/apps/marketplace/src/app/view/CustomApp.js
  src/apps/media/src/app/components/FolderMenu.tsx
  src/apps/media/src/app/components/Header.tsx
  src/apps/media/src/app/components/NewFolderDialog.tsx
  src/apps/media/src/app/components/Sidebar/Folders.tsx
  src/apps/media/src/app/components/Sidebar/index.tsx
  src/apps/media/src/app/components/UploadButton.tsx
  src/apps/media/src/app/index.tsx
  src/apps/media/src/app/views/AllMedia.tsx
  src/apps/media/src/app/views/BinMedia.tsx
  src/apps/media/src/app/views/FolderMedia.tsx
  src/apps/reports/src/app/ReportingApp.js
  src/apps/reports/src/app/components/ReportingNav.js
  src/apps/reports/src/app/components/ReportingNav.tsx
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
  src/apps/schema/src/app/components/DuplicateModelDialogue.tsx
  src/apps/schema/src/app/components/ModelHeader.tsx
  src/apps/schema/src/app/components/ModelMenu.tsx
  src/apps/schema/src/app/components/Sidebar/ModelList.tsx
  src/apps/schema/src/app/components/Sidebar/index.tsx
  src/apps/schema/src/app/index.tsx
  src/shell/components/AppSidebar/index.tsx
  src/shell/components/NavTree/components/NavTreeItem.tsx
  src/shell/components/NavTree/index.tsx
  src/shell/components/global-sidebar/components/InstanceAvatar.tsx
  src/shell/services/mediaManager.ts
  src/shell/services/types.ts
  src/shell/store/types.ts
Labels: ready, vqa, hand-off-ready

#2234 Feature: Global and App sidebar collapse update
  public/images/githubLogoSmall.svg
  public/images/zestyLogoOnlyGrey.svg
  src/apps/content-editor/src/app/components/ContentNav/index.tsx
  src/shell/components/ResizeableContainer.tsx
  src/shell/components/global-menu/index.tsx
  src/shell/components/global-sidebar/GlobalSidebar.tsx
  src/shell/components/global-sidebar/components/InstanceMenu/index.tsx
  src/shell/components/global-sidebar/components/OnboardingCall.tsx
  src/shell/views/Shell/Shell.less
Labels: ready, vqa
