Repository zesty-io/manager-ui, pull requests merged in 2023-09, with the labels that each got.

#2238 Feature/content title bar
  cypress/e2e/content/actions.spec.js
  cypress/e2e/content/analyticsDashboard.spec.js
  cypress/e2e/content/content.spec.js
  cypress/e2e/content/multi-lang.spec.js
  cypress/e2e/content/singlePageAnalytics.spec.js
  package-lock.json
  package.json
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/Editor.less
  src/apps/content-editor/src/app/components/PendingEditsModal/PendingEditsModal.js
  src/apps/content-editor/src/app/components/PendingEditsModal/PendingEditsModal.tsx
  src/apps/content-editor/src/app/views/Analytics/components/AnalyticsPropertySelector.tsx
  src/apps/content-editor/src/app/views/Analytics/index.tsx
  src/apps/content-editor/src/app/views/Analytics/views/SinglePageAnalytics/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/ActionsDrawer.less
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.less
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/ItemHead/ItemHead.js
  src/apps/content-editor/src/app/views/ItemEdit/ItemHead/ItemHead.less
  src/apps/content-editor/src/app/views/ItemEdit/Meta/Meta.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/Meta.less
  src/apps/content-editor/src/app/views/ItemEdit/PublishState.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ScheduleFlyout/ScheduleFlyout.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DeleteItemDialog.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuoModeToggle.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditBreadcrumbs.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/MoreMenu.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PreviewMenu.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/UnpublishDialog.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
  src/apps/home/app/index.tsx
  src/apps/media/src/app/components/FolderMenu.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
  src/apps/schema/src/app/components/ModelApi/ApiCard.tsx
  src/apps/schema/src/app/components/ModelApi/ApiCardList.tsx
  src/apps/schema/src/app/components/ModelApi/ApiDetails.tsx
  src/apps/schema/src/app/components/ModelHeader.tsx
  src/apps/schema/src/app/components/ModelMenu.tsx
  src/shell/components/CustomBreadcrumbs.tsx
  src/shell/components/Head/Head.less
  src/shell/constants.ts
  src/shell/services/instance.ts
  src/shell/store/content.js
  src/utility/formatDate.ts
Labels: ready, vqa

#2241 Feature: Media title bar
  cypress/e2e/home/mature.spec.js
  cypress/e2e/media/folders.spec.js
  cypress/e2e/schema/models.spec.js
  cypress/e2e/search/advanced-search.spec.js
  cypress/e2e/search/search-bar.spec.js
  cypress/e2e/search/search-page.spec.js
  public/images/uploadFiles.jpg
  public/images/uploadFiles.svg
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/media/src/app/components/Controls/Controls.tsx
  src/apps/media/src/app/components/Controls/DateFilter.tsx
  src/apps/media/src/app/components/Controls/FiletypeFilter.tsx
  src/apps/media/src/app/components/Controls/Sort.tsx
  src/apps/media/src/app/components/Controls/ToggleViews.tsx
  src/apps/media/src/app/components/EmptyState.tsx
  src/apps/media/src/app/components/FileModal/FileModalContent.tsx
  src/apps/media/src/app/components/Folder/index.tsx
  src/apps/media/src/app/components/Header.tsx
  src/apps/media/src/app/components/InsightsTable.tsx
  src/apps/media/src/app/components/MediaBreadcrumbs.tsx
  src/apps/media/src/app/components/MediaGrid.tsx
  src/apps/media/src/app/components/MediaList.tsx
  src/apps/media/src/app/components/Thumbnail/index.tsx
  src/apps/media/src/app/components/UploadModal.tsx
  src/apps/media/src/app/views/AllMedia.tsx
  src/apps/media/src/app/views/BinMedia.tsx
  src/apps/media/src/app/views/FolderMedia.tsx
  src/apps/media/src/app/views/InsightsMedia.tsx
  src/apps/media/src/app/views/SearchMedia.tsx
  src/shell/components/AppError/AppError.js
  src/shell/components/AppError/AppError.tsx
  src/shell/components/AppError/index.js
  src/shell/components/AppError/index.ts
  src/shell/components/CustomBreadcrumbs.tsx
Labels: ready, vqa

#2244 Fix: App crashing when creating single page model with no parent
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
Labels: ready

#2239 Fix: Add content nav highlight support for multi-lang content items
  src/apps/content-editor/src/app/components/ContentNav/index.tsx
Labels: ready

#2246 Feature: Schema title bar
  cypress/e2e/schema/activity-log.spec.js
  cypress/e2e/schema/models.spec.js
  package.json
  src/apps/content-editor/src/app/views/Analytics/views/AnalyticsDashboard/index.tsx
  src/apps/schema/src/app/components/AddFieldModal/FieldFormInput.tsx
  src/apps/schema/src/app/components/AddFieldModal/FieldItem.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/FieldSelection.tsx
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
  src/apps/schema/src/app/components/DuplicateModelDialogue.tsx
  src/apps/schema/src/app/components/Field/index.tsx
  src/apps/schema/src/app/components/FieldEmptyState.tsx
  src/apps/schema/src/app/components/FieldList.tsx
  src/apps/schema/src/app/components/FieldsListRight.tsx
  src/apps/schema/src/app/components/ModelActivityLog.tsx
  src/apps/schema/src/app/components/ModelApi/ApiCardList.tsx
  src/apps/schema/src/app/components/ModelApi/ApiDetails.tsx
  src/apps/schema/src/app/components/ModelBreadcrumbs.tsx
  src/apps/schema/src/app/components/ModelHeader.tsx
  src/apps/schema/src/app/components/ModelInfo/ActivityDetails.tsx
  src/apps/schema/src/app/components/ModelInfo/ModelDetails.tsx
  src/apps/schema/src/app/components/ModelInfo/RelatedModels.tsx
  src/apps/schema/src/app/components/ModelInfo/index.tsx
  src/apps/schema/src/app/components/ModelMenu.tsx
  src/apps/schema/src/app/components/ModelsTable.tsx
  src/apps/schema/src/app/components/Sidebar/index.tsx
  src/apps/schema/src/app/views/AllModels.tsx
  src/apps/schema/src/app/views/Model.tsx
  src/apps/schema/src/app/views/SearchModels.tsx
  src/shell/components/Filters/DateFilter/DateFilter.tsx
  src/shell/components/NotFound.tsx
Labels: vqa

#2265 Fix: Create item button overflow
  src/apps/content-editor/src/app/ContentEditor.less
  src/apps/content-editor/src/app/views/ItemList/ItemList.js
Labels: ready
