Repository zesty-io/manager-ui, pull requests merged in 2023-11, with the labels that each got.

#2327 Chore: Remove unused components
  src/shell/components/GlobalHelpMenu/GlobalHelpMenu.js
  src/shell/components/GlobalHelpMenu/GlobalHelpMenu.less
  src/shell/components/GlobalHelpMenu/index.js
  src/shell/components/NotFound/NotFound.js
  src/shell/components/NotFound/NotFound.less
  src/shell/components/NotFound/index.js
  src/shell/components/global-account/GlobalAccount.js
  src/shell/components/global-account/GlobalAccount.less
  src/shell/components/global-account/GlobalAccount.spec.js
  src/shell/components/global-account/index.js
  src/shell/components/global-actions/index.js
  src/shell/components/global-actions/styles.less
  src/shell/components/global-instance/GlobalInstance.js
  src/shell/components/global-instance/GlobalInstance.less
  src/shell/components/global-instance/index.js
Labels: ready

#2333 Scope error handling to action
  src/shell/store/content.js
Labels: bug, ready

#2328 Item list header button layout fix
  src/apps/content-editor/src/app/views/ItemList/SetActions/SetActions.less
Labels: bug, ready

#2330 Show an asterisk to required fields
  src/apps/schema/src/app/components/Field/index.tsx
Labels: enhancement, ready, vqa

#2345 Re-add logic to show announcement based off of start and end dates
  src/shell/components/InAppAnnouncement/index.tsx
Labels: bug

#2351 Handle replace edge case when selecting an image that is already in the field
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: ready

#2352 Show limit selection as 1 in UI when replacing image
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: ready

#2357 Dont allow duplicate media items in media field
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: ready

#2361 Preview scale on devices should be 100%
  src/apps/active-preview/Preview.js
Labels: ready

#2363 Make read announcements cookie permanent
  src/shell/components/InAppAnnouncement/index.tsx
Labels: bug
