Repository zesty-io/manager-ui, pull requests merged in 2023-12, with the labels that each got.

#2362 Minor media field enhancements
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: vqa

#2372 Various WYSIWYG enhancements
  src/apps/content-editor/src/app/components/Editor/Field/FieldShell.tsx
  src/shell/components/FieldTypeTinyMCE/FieldTypeTinyMCE.js
Labels: bug, enhancement, ready, vqa

#2384 Focus mode improvements
  src/apps/content-editor/src/app/components/Editor/Field/FieldShell.tsx
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
Labels: ready, vqa

#2335 Media modal enhancements
  src/apps/media/src/app/components/FileModal/DeleteFileModal.tsx
  src/apps/media/src/app/components/FileModal/FileModalContent.tsx
  src/apps/media/src/app/components/FileModal/FileTypePreview.tsx
  src/apps/media/src/app/components/FileModal/index.tsx
  src/apps/media/src/app/components/Thumbnail/ThumbnailContent.tsx
  src/apps/media/src/app/components/Thumbnail/index.tsx
  src/apps/media/src/app/components/UploadModal.tsx
Labels: enhancement, vqa

#2402 In-app announcement timezone
  src/shell/components/InAppAnnouncement/index.tsx
Labels: bug, ready

#2406 Cypress test runner use old chrome headless
  cypress.config.js
Labels: maintenance

#2382 Single page analytics UX Enhancements
  src/apps/content-editor/src/app/views/Analytics/components/CompareDialog.tsx
  src/apps/content-editor/src/app/views/Analytics/utils.ts
  src/apps/content-editor/src/app/views/Analytics/views/SinglePageAnalytics/ByDayLineChart.tsx
  src/apps/content-editor/src/app/views/Analytics/views/SinglePageAnalytics/UsersBarChart.tsx
  src/apps/content-editor/src/app/views/Analytics/views/SinglePageAnalytics/UsersDoughnutChart.tsx
  src/apps/content-editor/src/app/views/Analytics/views/SinglePageAnalytics/index.tsx
Labels: enhancement, ready, vqa

#2401 Confirm publish modal
  cypress/e2e/content/actions.spec.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ConfirmPublishModal.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/UnpublishDialog.tsx
  src/shell/store/content.js
Labels: enhancement, ready, vqa

#2408 Send post message to active preview opened in new tab
  src/apps/active-preview/Preview.js
Labels: ready

#2407 Various media bug fixes
  package-lock.json
  package.json
  src/apps/media/src/app/components/FileModal/OTFEditor.tsx
  src/apps/media/src/app/components/Header.tsx
Labels: bug, vqa
