Repository zesty-io/manager-ui, pull requests merged in 2024-03, with the labels that each got.

#2551 Fix/update font weight 700
  package-lock.json
  package.json
  src/apps/content-editor/src/app/components/PendingEditsModal/PendingEditsModal.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ConfirmPublishModal.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DeleteItemDialog.tsx
  src/apps/schema/src/app/components/DeleteModelDialogue.tsx
  src/apps/schema/src/app/components/RenameModelDialogue.tsx
  src/shell/components/login/Login.js
Labels: ready, vqa

#2567 Add tooltips to content title bar buttons
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuoModeToggle.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/MoreMenu.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PreviewMenu.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
Labels: enhancement, ready, vqa

#2579 Allow spaces and capital letters in dropdown value
  src/apps/schema/src/app/components/AddFieldModal/FieldFormInput.tsx
  src/apps/schema/src/app/utils/index.ts
Labels: bug, ready, vqa

#2573 fix: Content: Confirm Publish Modal - Publish Button does not always get focussed
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ConfirmPublishModal.tsx
Labels: ready, vqa

#2583 schema ui enhancements
  src/apps/schema/src/app/components/AddFieldModal/ComingSoon.tsx
  src/apps/schema/src/app/components/AddFieldModal/FieldFormInput.tsx
  src/apps/schema/src/app/components/configs.ts
Labels: enhancement, ready, vqa

#2519 fix : Content: No Fields Have Been Added Screen appears for Content Items that have fields
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
Labels: ready, vqa

#2569 Fallback to created by user data if audit info not available
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
Labels: ready, vqa

#2591 Only return files that belong to the bins group
  src/shell/services/mediaManager.ts
Labels: ready, vqa

#2594 Convert media spaces in media filename to dashes
  src/apps/media/src/app/components/FileModal/RenameFileModal.tsx
  src/apps/media/src/app/components/Thumbnail/ThumbnailContent.tsx
Labels: enhancement, ready, vqa

#2590 fix: Content: SEO Tab - Title Bar reflects Published State
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
Labels: ready, vqa

#2613 Add settings resource route in activity log
  src/apps/reports/src/app/views/ActivityLog/views/ResourceDetails.js
  src/shell/services/types.ts
  src/utility/resolveResourceUrlFromAudit.ts
Labels: bug, ready

#2566 Number field revamp
  cypress/e2e/content/content.spec.js
  package-lock.json
  package.json
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/shell/components/FieldTypeNumber.tsx
  src/shell/components/NumberFormatInput/index.tsx
Labels: enhancement, ready, vqa

#2589 fix: Media: Upload Modal - Title does not become plural
  src/apps/media/src/app/components/UploadModal.tsx
Labels: ready, vqa
