Repository zesty-io/manager-ui, pull requests merged in 2024-02, with the labels that each got.

#2512 Only scroll to error blurb on field errors mount
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/FieldError.tsx
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
Labels: bug, ready, vqa

#2500 Prevent tinymce from triggering onChange on initial load
  src/shell/components/CreateContentItemDialog.tsx
  src/shell/components/FieldTypeTinyMCE/index.tsx
Labels: bug, ready, vqa

#2484 Create content item fields width
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
Labels: enhancement, ready, vqa

#2473 Do not unmount shell when session expires
  src/shell/components/load-instance/index.js
  src/shell/components/private-route/index.js
Labels: enhancement, ready

#2514 Fix: Copy the meta description when content item is duplicated
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx
Labels: vqa

#2453 Add media field thumbnails
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
  src/apps/media/src/app/components/FileModal/FileTypePreview.tsx
  src/apps/media/src/app/utils/fileUtils.ts
Labels: bug, ready, vqa

#2528 Enable HTML editor line wrapping
  src/shell/components/FieldTypeEditor/Editors/Html.js
Labels: bug

#2536 Fit long file names into delete file modal
  src/apps/media/src/app/components/FileModal/DeleteFileModal.tsx
Labels: bug, ready

#2533 Apply focus mode only layout changes
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
Labels: ready, vqa

#2539 Schema: Rename Integer Field Type to Number Field Type
  src/apps/schema/src/app/components/configs.ts
Labels: enhancement, ready, vqa

#2544 Duo mode modal enhancements
  src/apps/active-preview/Preview.js
  src/apps/content-editor/src/app/components/Editor/PreviewMode/PreviewMode.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
Labels: enhancement, ready, vqa

#2521 Exclude option items that are not saved / published /scheduled
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/shell/store/content.js
Labels: bug, ready, vqa

#2557 Disable toggle fields unselect
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
Labels: bug, ready

#2552 Sort field revamp
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/shell/components/FieldTypeSort/index.tsx
Labels: enhancement, ready, vqa

#2550 Prevent login screen from briefly flashing on page reload
  src/shell/components/private-route/index.js
Labels: bug, ready

#2534 fix: Content: SEO Meta Description Displays that there are excess characters when there are none
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ItemSettings.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/Meta.js
  src/shell/store/content.js
Labels: bug, vqa

#2520 Invite user enhancements
  src/shell/components/InviteMembersModal/ConfirmationDialog.tsx
  src/shell/components/InviteMembersModal/NoPermission.tsx
  src/shell/components/InviteMembersModal/RoleAccessInfo.tsx
  src/shell/components/InviteMembersModal/RoleSelectModal.tsx
  src/shell/components/InviteMembersModal/index.tsx
  src/shell/components/load-instance/index.js
  src/utility/pluralizeWord.ts
Labels: enhancement, ready, vqa

#2541 fix: Content: SEO Tab - Select Page Parent Dropdown is showing the same route multiple times
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/ItemParent.js
Labels: ready, vqa

#2543 Load image urls in media field preview
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: bug, ready

#2558 fix: Global Nav: Bug Fixes
  src/shell/components/GlobalAccountMenu/index.tsx
  src/shell/components/global-notifications/GlobalNotifications.less
Labels: ready, vqa

#2570 Update activity log logic to distinguish Scheduled vs Published actions
  src/apps/reports/src/app/views/ActivityLog/components/ActionTimelineItem/TimelineItem.js
  src/shell/services/instance.ts
Labels: bug, ready, vqa

#2564 Prevent verify from invalidating stores
  src/shell/components/GlobalAccountMenu/index.tsx
  src/shell/components/load-instance/index.js
  src/shell/store/types.ts
Labels: bug
