Repository zesty-io/manager-ui, pull requests merged in 2024-01, with the labels that each got.

#2419 Undefined meta description error
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/MetaDescription.js
Labels: bug, ready

#2409 Global search fixes
  src/shell/components/GlobalSearch/components/AdvancedSearch.tsx
  src/shell/components/GlobalSearch/index.tsx
  src/shell/components/withCursorPosition/index.tsx
  src/shell/views/SearchPage/SearchPage.tsx
Labels: ready, vqa

#2423 Auto focus publish button on confirm publish dialog
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ConfirmPublishModal.tsx
Labels: vqa

#2429 Add missing parent path
  src/apps/schema/src/app/components/ModelApi/ApiDomainEndpoints.tsx
Labels: bug, ready

#2438 Fix create and publish button functionality
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
Labels: ready, vqa

#2439 Reset Save & Publish button loading status when field has errors
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
Labels: bug

#2445 Resolve SEO fields lag
  src/apps/content-editor/src/app/ContentEditor.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ItemSettings.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/ItemParent.js
  src/shell/components/global-tabs/GlobalTabs.tsx
Labels: bug

#2446 Limit media upload on content edit image field to locked group
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: vqa

#2447 Content app UI fixes
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetDeleteItem/WidgetDeleteItem.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/shell/components/ResizeableContainer.tsx
Labels: bug, vqa

#2462 Add AI to legacy instance
  src/shell/components/withAi/index.tsx
Labels: ready

#2461 Convert empty string values as null, scroll to error blurb instead of errored field
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/FieldError.tsx
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
Labels: ready, vqa

#2444 Remove content item data keys that are no longer valid when item is being created
  src/shell/store/content.js
Labels: vqa

#2472 Change in-app announcement image resolution
  src/shell/components/InAppAnnouncement/index.tsx
Labels: bug, vqa
