Repository zesty-io/manager-ui, pull requests merged in 2024-05, with the labels that each got.

#2678 Schedule content item publish revamp
  cypress/e2e/content/actions.spec.js
  package-lock.json
  package.json
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Meta/Meta.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ItemVersioning.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ItemVersioning.less
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ScheduleFlyout/ScheduleFlyout.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ScheduleFlyout/ScheduleFlyout.less
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/ScheduleFlyout/index.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/VersionSelector/VersionSelector.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/VersionSelector/VersionSelector.less
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/VersionSelector/index.js
  src/apps/content-editor/src/app/views/ItemEdit/components/Header/ItemVersioning/index.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ConfirmPublishModal.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PreviewMenu.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
  src/shell/components/FieldTypeDate/index.tsx
  src/shell/components/FieldTypeDateTime/index.tsx
  src/shell/components/FieldTypeDateTime/util.ts
  src/shell/components/SchedulePublish/index.tsx
  src/shell/services/types.ts
Labels: ready

#2717 Zesty material version bump
  package-lock.json
  package.json
Labels: enhancement, ready

#2725 Allow duplication of dataset items with no title, link text and description
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx
Labels: bug, ready

#2727 Place current system timezone and UTC to top of list
  src/shell/components/FieldTypeDateTime/index.tsx
  src/shell/components/FieldTypeDateTime/util.ts
  src/shell/components/SchedulePublish/index.tsx
Labels: ready

#2712 Publish status labels
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/QuickView/QuickView.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/QuickView/QuickView.less
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/QuickView/index.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PublishStatus.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
Labels: enhancement, ready

#2555 feat: Global: Notification Alert Revamp
  cypress/e2e/content/actions.spec.js
  cypress/e2e/content/content.spec.js
  package-lock.json
  package.json
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ItemSettings.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/ItemParent.js
  src/apps/content-editor/src/app/views/LinkCreate/LinkCreate.js
  src/apps/content-editor/src/app/views/LinkEdit/LinkEdit.js
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
  src/apps/schema/src/app/components/DeleteModelDialogue.tsx
  src/apps/schema/src/app/components/Field/index.tsx
  src/shell/components/global-notifications/GlobalNotifications.js
  src/shell/store/notifications.ts
Labels: ready
