Repository zesty-io/manager-ui, pull requests merged in 2024-04, with the labels that each got.

#2584 fix: Preview Modal - Disable the Arrow Key Image Changing Functionality
  src/apps/media/src/app/components/FileModal/index.tsx
Labels: ready, vqa

#2562 Date field revamp
  cypress/e2e/content/content.spec.js
  package-lock.json
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/shell/components/FieldTypeDate/index.tsx
Labels: enhancement, ready

#2581 Bynder integration
  cypress/e2e/content/content.spec.js
  package-lock.json
  package.json
  public/icons/material-rounded/icons.js
  public/images/bynder-logo.svg
  public/images/bynder-preview.png
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
  src/apps/media/src/app/components/FileModal/FileTypePreview.tsx
  src/apps/settings/src/app/App.js
  src/apps/settings/src/app/components/Nav/SettingsNav.tsx
  src/apps/settings/src/app/views/Bynder.tsx
  src/shell/components/FieldTypeTinyMCE/index.tsx
Labels: ready, feature

#2549 Content: UUID Field Revamp
  package-lock.json
  src/apps/schema/src/app/components/AddFieldModal/TooltipBody.tsx
  src/shell/components/FieldTypeUUID/FieldTypeUUID.js
Labels: enhancement, ready

#2540 Fix/2432 add field tooltip styling
  package-lock.json
  src/apps/schema/src/app/components/AddFieldModal/TooltipBody.tsx
Labels: enhancement, ready

#2672 Date field revamp vqa updates
  src/shell/components/FieldTypeDate/index.tsx
Labels: ready

#2677 Change internal link none value from "0" to null
  src/shell/components/FieldTypeInternalLink/FieldTypeInternalLink.js
Labels: bug, ready

#2664 Date & Time Field revamp
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/shell/components/FieldTypeDate/index.tsx
  src/shell/components/FieldTypeDateTime/index.tsx
  src/shell/components/FieldTypeDateTime/util.ts
Labels: enhancement, ready

#2680 Date and datetime field timezone fixes
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/shell/components/FieldTypeDateTime/index.tsx
Labels: ready

#2682 Update new date field value format and added value preview
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/shell/components/FieldTypeDate/index.tsx
  src/shell/components/FieldTypeDateTime/index.tsx
Labels: ready

#2690 Date and date time field vqa updates
  src/shell/components/FieldTypeDate/index.tsx
  src/shell/components/FieldTypeDateTime/index.tsx
  src/shell/components/FieldTypeDateTime/util.ts
Labels: ready

#2692 Convert dates used in the activity log api calls to UTC
  src/apps/reports/src/app/views/ActivityLog/utils.ts
  src/apps/reports/src/app/views/ActivityLog/views/Home.js
  src/apps/reports/src/app/views/ActivityLog/views/ResourceDetails.js
  src/apps/reports/src/app/views/ActivityLog/views/UserDetails.js
  src/apps/schema/src/app/components/ModelActivityLog.tsx
Labels: bug, ready

#2696 Truncate text when duplicating item
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx
Labels: bug, ready

#2698 Predict year while typing in date string
  src/shell/components/FieldTypeDate/index.tsx
Labels: ready
