Repository zesty-io/manager-ui, pull requests merged in 2024-06, with the labels that each got.

#2730 Schedule publish modal and publish status indicator vqa updates
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PublishStatus.tsx
  src/shell/components/FieldTypeDateTime/index.tsx
  src/shell/components/FieldTypeDateTime/util.ts
  src/shell/store/content.js
Labels: ready

#2718 Fix: Displaying Invalid date for Publish Date
  src/apps/reports/src/app/views/ActivityLog/components/ActionTimelineItem/TimelineItem.js
Labels: ready

#2736 Change schedule tooltip wording
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PublishStatus.tsx
Labels: ready

#2741 Schedule publish modal vqa updates
  src/shell/components/FieldTypeDateTime/index.tsx
Labels: enhancement, ready

#2709 Reset user data on logout
  src/shell/store/auth.js
  src/shell/store/user.js
Labels: bug, ready

#2711 Comment System
  README.md
  cypress/e2e/content/comments.js
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/components/Editor/Field/FieldShell.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
  src/shell/components/Comment/CommentItem.tsx
  src/shell/components/Comment/CommentsList.tsx
  src/shell/components/Comment/ConfirmDeleteModal.tsx
  src/shell/components/Comment/InputField.tsx
  src/shell/components/Comment/MentionList.tsx
  src/shell/components/Comment/index.tsx
  src/shell/components/Comment/utils.ts
  src/shell/components/FieldTypeTinyMCE/index.tsx
  src/shell/contexts/CommentProvider.tsx
  src/shell/index.js
  src/shell/services/accounts.ts
  src/shell/services/types.ts
Labels: ready, feature

#2755 Schema min/max characters rule
  cypress/e2e/content/actions.spec.js
  cypress/e2e/schema/field.spec.js
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/Editor/Field/FieldShell.tsx
  src/apps/content-editor/src/app/components/Editor/Field/FieldTooltipBody.tsx
  src/apps/content-editor/src/app/components/Editor/FieldError.tsx
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/schema/src/app/components/AddFieldModal/CharacterLimit.tsx
  src/apps/schema/src/app/components/AddFieldModal/FieldFormInput.tsx
  src/apps/schema/src/app/components/AddFieldModal/Learn.tsx
  src/apps/schema/src/app/components/AddFieldModal/MediaRules.tsx
  src/apps/schema/src/app/components/AddFieldModal/Regex.tsx
  src/apps/schema/src/app/components/AddFieldModal/index.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/Rules.tsx
  src/apps/schema/src/app/components/Field/index.tsx
  src/apps/schema/src/app/components/configs.ts
  src/shell/components/FieldTypeNumber.tsx
  src/shell/services/types.ts
  src/shell/store/content.js
Labels: enhancement, ready

#2770 [Schema Rules] Only show error blurb when user clicks Save
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
Labels: bug, ready
