Repository zesty-io/manager-ui, pull requests merged in 2024-11, with the labels that each got.

#3044 [Content] Support dedicated TC Image field in SEO tab
  cypress/e2e/content/meta.spec.js
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/TwitterPreview.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/useImageURL.ts
  src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Meta/settings/MetaImage.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Meta/settings/TCImage.tsx
Labels: enhancement, ready

#3067 [Content] Add field zuid as id for tc_image
  src/apps/content-editor/src/app/views/ItemEdit/Meta/settings/TCImage.tsx
Labels: bug, ready

#3060 [Content] Auto-select first field when popup opens
  src/shell/components/withAi/AIGenerator.tsx
Labels: enhancement, ready

#3059 [Content] Prevent users with no first or last names from crashing the app
  src/shell/components/Comment/MentionList.tsx
Labels: bug, ready

#3061 CSV Download
  src/apps/content-editor/src/app/views/ItemList/ItemListActions.tsx
  src/shell/app.config.js
  src/shell/services/cloudFunctions.ts
Labels: feature
