Repository zesty-io/manager-ui, pull requests merged in 2025-01, with the labels that each got.

#3121 [Blocks] Navigate to created block on successful creation
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
Labels: bug, ready

#3122 [3116]#SEO-Tab-Page-Parent-Dropdown: Enhanced sorting logic with adde…
  src/apps/content-editor/src/app/views/ItemEdit/Meta/settings/ItemParent.tsx
  src/shell/components/GlobalSearch/utils.ts
Labels: enhancement, ready

#3118 Added the 'Insert/Edit Link' button and moved the 'Remove Format' but…
  src/shell/components/FieldTypeTinyMCE/index.tsx
Labels: enhancement, ready

#3090 [Content | Schema] Block Selector
  cypress/e2e/content/content.spec.js
  cypress/e2e/schema/field.spec.js
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/Editor/Field/FieldShell.tsx
  src/apps/content-editor/src/app/components/Editor/FieldError.tsx
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/schema/src/app/components/AddFieldModal/views/FieldSelection.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/Rules.tsx
  src/apps/schema/src/app/components/Field/FieldIcon.tsx
  src/apps/schema/src/app/components/configs.ts
  src/apps/schema/src/app/utils/index.ts
  src/shell/components/FieldTypeBlockSelector/NoVariant.tsx
  src/shell/components/FieldTypeBlockSelector/VariantSelector.tsx
  src/shell/components/FieldTypeBlockSelector/index.tsx
  src/shell/components/NoSearchResults/index.tsx
  src/shell/services/instance.ts
  src/shell/store/content.js
Labels: ready, feature

#3133 [Schema] Prevent app from crashing when field settings is null
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
Labels: bug, ready

#3119 Refactor hover effect: Use mouse events to trigger hover state for be…
  src/shell/components/NavTree/components/NavTreeItem.tsx
  src/shell/components/NavTree/index.tsx
Labels: enhancement, ready

#3142 [Content | Schema] Block Selector VQA
  cypress/e2e/content/content.spec.js
  cypress/e2e/content/navigation.spec.js
  src/apps/blocks/views/BlockModel.tsx
  src/apps/schema/src/app/utils/index.ts
  src/shell/components/FieldTypeBlockSelector/NoVariant.tsx
  src/shell/components/FieldTypeBlockSelector/VariantSelector.tsx
  src/shell/components/FieldTypeBlockSelector/index.tsx
Labels: ready

#3145 Block Selector VQA Updates 2
  cypress/e2e/content/content.spec.js
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
  src/shell/components/FieldTypeBlockSelector/VariantSelector.tsx
  src/shell/components/FieldTypeBlockSelector/index.tsx
Labels: ready
