Repository zesty-io/manager-ui, pull requests merged in 2025-02, with the labels that each got.

#3180 [Schema] Add visual highlight to currently active sorting order
  src/apps/schema/src/app/components/Sidebar/ModelList.tsx
Labels: enhancement, ready

#3184 [Content] One-to-one/many Revamp Phase 1
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/UnpublishedRelatedItem.tsx
  src/shell/components/ConfirmPublishModal.tsx
  src/shell/components/Filters/FilterButton.tsx
  src/shell/components/RelationalFieldBase/ActiveItem/ActiveItemLoading.tsx
  src/shell/components/RelationalFieldBase/ActiveItem/index.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/DialogHeader.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/FieldSelectorFilters.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/ImageCell.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/ItemsLoading.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/TitleCell.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/VersionCell.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
  src/shell/components/RelationalFieldBase/VersionChip.tsx
  src/shell/components/RelationalFieldBase/index.tsx
  src/shell/components/SchedulePublish/index.tsx
Labels: enhancement, ready

#3194 [Content | Schema] VQA updates for the one-to-one/many revamp
  cypress/e2e/schema/field.spec.js
  src/apps/schema/src/app/components/AddFieldModal/DefaultValueInput.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
  src/shell/components/RelationalFieldBase/index.tsx
Labels: ready

#3198 [Content | Schema] VQA Round 2 updates for the one-to-one/many revamp
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/UnpublishedRelatedItem.tsx
  src/apps/schema/src/app/components/AddFieldModal/DefaultValue.tsx
  src/apps/schema/src/app/components/AddFieldModal/DefaultValueInput.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/Rules.tsx
  src/shell/components/ConfirmPublishModal.tsx
  src/shell/components/NoSearchResults/index.tsx
  src/shell/components/RelationalFieldBase/ActiveItem/ActiveItemLoading.tsx
  src/shell/components/RelationalFieldBase/ActiveItem/index.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/DialogHeader.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
  src/shell/components/RelationalFieldBase/index.tsx
Labels: ready

#3214 Handle all failed network request errors
  src/shell/store/content.js
  src/shell/store/fields.js
  src/shell/store/headTags.js
  src/shell/store/media.js
  src/shell/store/models.js
Labels: bug, ready

#3227 [Content] Filter out deleted fields in FieldForm dropdown options
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
Labels: bug, ready

#3225 Content: WYSIWYG - Command P or Ctrl P does not trigger the Save and Publish and the Publish Button
  src/shell/components/FieldTypeTinyMCE/index.tsx
Labels: bug

#3221 [Schema] Auto-populate relational field name & label
  cypress/e2e/schema/field.spec.js
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
Labels: enhancement, ready

#3239 [Content] Preserve selections from being cleared when filtering items in relational fields
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/dateFilter.ts
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/keywordSearchFilter.ts
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/statusFilter.ts
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/userFilter.ts
Labels: bug, ready

#3203 [Content] Create new item from one to many field
  cypress/e2e/content/content.spec.js
  src/apps/content-editor/src/app/ContentEditor.js
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/Editor/Field/InternalLink.tsx
  src/apps/content-editor/src/app/views/ItemCreate/Header.tsx
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/schema/src/app/components/AddFieldModal/DefaultValueInput.tsx
  src/shell/components/RelationalFieldBase/CreateNewItemDialog.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
  src/shell/components/RelationalFieldBase/index.tsx
  src/shell/contexts/CreateContentItemDialogProvider.tsx
  src/shell/index.js
Labels: enhancement, ready

#3240 Ensure promise rejection is always of an Error instance
  src/utility/request.js
Labels: bug, ready

#3233 [Global] Favicon selection enhancement
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
  src/shell/components/Favicon/favicon.less
  src/shell/components/Favicon/index.tsx
  src/shell/components/favicon/favicon.js
  src/shell/components/favicon/index.js
  src/shell/components/global-sidebar/GlobalSidebar.tsx
Labels: enhancement, ready
