Repository zesty-io/manager-ui, pull requests merged in 2025-06, with the labels that each got.

#3559 [Content] Show an asterisk to required fields during model field creation
  src/apps/schema/src/app/components/AddFieldModal/FieldFormInput.tsx
Labels: enhancement, ready

#3572 Feature/3524 preserve scroll position when editing block variants
  src/apps/blocks/index.tsx
  src/apps/blocks/views/BlockItem.tsx
Labels: enhancement

#3582 [Content] Clear wysiwyg char length error when value is updated
  src/apps/content-editor/src/app/components/Editor/Editor.js
Labels: bug, ready

#3522 [#3444] Content: Create Redirect on URL Path Update
  src/apps/content-editor/src/app/views/ItemEdit/Meta/IncomingRedirects/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
  src/apps/content-editor/src/app/views/Redirects/ContentRedirects.tsx
  src/apps/content-editor/src/app/views/Redirects/index.tsx
  src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx
  src/apps/seo/src/app/components/RedirectsDialogProvider/CreateRedirects/CreateForm.tsx
  src/apps/seo/src/app/components/RedirectsDialogProvider/index.tsx
Labels: enhancement

#3586 [#3585] : Blocks - Newly-created variant doesn't get added to the variants list tab
  src/apps/blocks/components/CreateVariantDialog.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx
  src/shell/services/instance.ts
  src/shell/store/content.js
Labels: bug

#3588 [#3587] : Launchpad - Empty summary page is not properly laid out
  cypress/e2e/content/actions.spec.js
  src/apps/home/app/components/EmptyState.tsx
Labels: enhancement

#3607 [Content] Fallback to modelZUID when viewing quick access API from multipage table
  src/apps/content-editor/src/app/components/APIEndpoints.tsx
  src/apps/content-editor/src/app/views/ItemList/ItemListActions.tsx
Labels: bug, ready

#3555 [#3499] Content: Unable to Create New Item - Required Field Error
  src/apps/schema/src/app/utils/index.ts
  src/shell/store/content.js
Labels: bug

#3610 [Content] Prevent viewport from scrolling up when programatically scrolling to a field
  src/shell/views/Shell/Shell.tsx
Labels: bug, ready

#3619 [#3611]: Redirects - Unable to use '$' in redirect target when using a wildcard redirect
  src/apps/seo/src/app/components/RedirectsDialogProvider/CreateRedirects/PathField.tsx
Labels: bug

#3614 [Content] Properly import and set prosemirror plugins
  src/shell/components/FieldTypeEditor/Editors/react-prosemirror-plugins/index.js
  src/shell/components/FieldTypeEditor/Editors/react-prosemirror-plugins/plugins.js
Labels: bug, ready

#3617 [Code] Automatically open create new file dialog when create code file is selected on launchpad FAB
  cypress/e2e/code/all-files-page.spec.js
  src/apps/code-editor/src/app/components/RecentFiles/index.tsx
Labels: bug, ready

#3627 Resolve non-promise rejections from unhandled rtk query unwrap()
  src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/useImageURL.ts
  src/apps/content-editor/src/app/views/ItemEdit/Meta/settings/MetaImage.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
Labels: bug, ready

#3621 [Activity Log] Show workflow status name instead of workflow status ZUID
  src/apps/reports/src/app/views/ActivityLog/components/ActionTimelineItem/TimelineItem.js
  src/apps/reports/src/app/views/ActivityLog/components/ResourceHeaderTitle.tsx
  src/apps/reports/src/app/views/ActivityLog/components/ResourceListItem/SettingsResourceListItem.js
Labels: enhancement, ready
