Repository zesty-io/manager-ui, pull requests merged in 2025-04, with the labels that each got.

#3337 [Content] Set the no results component as a NoRowsOverlay prop in Datagrid
  src/apps/content-editor/src/app/views/ItemList/ItemListTable.tsx
  src/apps/content-editor/src/app/views/ItemList/index.tsx
Labels: bug, ready

#3332 [Content] Multipage row selection enhancements
  src/apps/content-editor/src/app/views/ItemList/ItemListTable.tsx
Labels: enhancement, ready

#3338 [Content] Localize internal link related item ZUID resolution
  src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
  src/apps/content-editor/src/app/components/Editor/Field/InternalLink.tsx
Labels: bug, ready

#3362 Fix/code app UI ux improvements
  src/apps/code-editor/src/app/components/BottomDrawer/FileCard.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/FileStatus.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/LinkedContent.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/LinkedSchema.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/index.tsx
  src/apps/code-editor/src/app/components/Differ/Differ.js
  src/apps/code-editor/src/app/components/Editor/Editor.js
  src/apps/code-editor/src/app/components/Editor/components/MemoizedEditor/MemoizedEditor.js
  src/apps/code-editor/src/app/components/SideBar/CreateFile.tsx
  src/apps/code-editor/src/app/components/SideBar/FileNav.tsx
  src/apps/code-editor/src/app/components/SideBar/OrderFiles.tsx
  src/apps/code-editor/src/app/components/SideBar/OrderFiles/Draggable.js
  src/apps/code-editor/src/app/components/SideBar/index.tsx
  src/apps/code-editor/src/app/components/TopBar/ActionButton.tsx
  src/apps/code-editor/src/app/components/TopBar/DeleteDialog.tsx
  src/apps/code-editor/src/app/components/TopBar/DifferActions.tsx
  src/apps/code-editor/src/app/components/TopBar/EditorActions.tsx
  src/apps/code-editor/src/app/components/TopBar/index.tsx
  src/apps/code-editor/src/app/components/Workspace/index.js
  src/apps/code-editor/src/app/views/CodeEditor/CodeEditor.js
  src/apps/code-editor/src/store/files.js
  src/apps/code-editor/src/store/navCode.js
  src/shell/components/NavTree/components/NavTreeItem.tsx
  src/shell/components/global-tabs/components/Tab.tsx
  src/shell/index.js
Labels: bug, enhancement

#3380 [Content] Make sure ref exists before calculating offsets
  src/shell/components/Comment/CommentsList.tsx
Labels: bug, ready

#3388 [#3368] : Settings: UX Enhancements
  cypress/e2e/settings/actions.spec.js
  cypress/e2e/settings/instance.spec.js
  src/apps/settings/src/app/App.js
  src/apps/settings/src/app/App.less
  src/apps/settings/src/app/components/ConfirmSaveDialog.tsx
  src/apps/settings/src/app/components/Containers.tsx
  src/apps/settings/src/app/components/TopBar.tsx
  src/apps/settings/src/app/views/Fonts/Browse.js
  src/apps/settings/src/app/views/Fonts/Installed.js
  src/apps/settings/src/app/views/Instance/Instance.js
  src/apps/settings/src/app/views/Instance/SettingsStyles.less
  src/apps/settings/src/app/views/Robots/HeadTags.js
  src/apps/settings/src/app/views/Robots/Robots.js
  src/apps/settings/src/app/views/Robots/Robots.less
  src/apps/settings/src/app/views/Styles/Styles.js
  src/apps/settings/src/app/views/Styles/Styles.less
  src/shell/store/settings.js
Labels: enhancement

#3376 [#3366]: Redirects: Delete Redirect Confirmation Modal
  src/apps/seo/src/store/redirects.js
  src/apps/seo/src/views/RedirectsManager/RedirectsTable/DeleteDialog.tsx
  src/apps/seo/src/views/RedirectsManager/RedirectsTable/RedirectCreator/RedirectCreator.js
  src/apps/seo/src/views/RedirectsManager/RedirectsTable/RedirectTable.js
  src/shell/index.js
Labels: enhancement

#3390 [#3387] Code App: Titlebar - Display Version Number adjacent to File …
  src/apps/code-editor/src/app/components/TopBar/index.tsx
Labels: enhancement

#3424 [#3417]: Blocks: All Blocks Page - Create Block Button in the Title Bar opens wrong modal ('Select Model Type')
  src/apps/blocks/views/AllBlocks.tsx
Labels: bug

#3224 [Content] Improve image thumbnails
  src/apps/content-editor/src/app/views/ItemList/TableCells/ImageCell.tsx
  src/apps/content-editor/src/app/views/ItemList/index.tsx
  src/shell/components/Favicon/index.tsx
Labels: bug, ready

#3425 [#3400] Code: Sidebar - Expand List Items in Search Results
  public/images/sb__hero__image__2.png
  src/apps/code-editor/src/app/components/SideBar/FileNav.tsx
  src/apps/code-editor/src/app/components/SideBar/index.tsx
  src/shell/components/NavTree/index.tsx
Labels: enhancement

#3452 [Content] Default to 0 when a user deletes all input field value
  src/apps/content-editor/src/app/views/ItemList/TableCells/SortCell.tsx
Labels: bug, ready

#3455 [Global] Semi-transparent resume session backdrop
  src/shell/components/login/Login.js
  src/shell/components/private-route/index.js
Labels: enhancement, ready
