Repository zesty-io/manager-ui, pull requests merged in 2025-07, with the labels that each got.

#3618 [Global] Prevent AI drawer from overflowing browser width
  src/apps/content-editor/src/app/views/Analytics/views/AnalyticsDashboard/ItemsTable/ItemsTable.tsx
  src/apps/home/app/components/ResourceTable.tsx
Labels: bug, ready

#3609 [Activity Log] Show lang code on a content item if the instance has multi lang
  src/apps/reports/src/app/views/ActivityLog/components/ResourceHeaderTitle.tsx
  src/apps/reports/src/app/views/ActivityLog/components/ResourceListItem/ContentResourceListItem.js
  src/shell/services/instance.ts
Labels: enhancement, ready

#3633 [Global] Prevent unnecessary re-renders in global top bar
  src/shell/components/GlobalTopbar/GlobalTopbar.tsx
  src/shell/components/global-tabs/components/Tab.tsx
  src/shell/store/ui.ts
Labels: enhancement, ready

#3666 [#3665]: Global - App Crashes When Rendering Login Page for Logged-Out Users
  src/shell/components/GlobalSearch/index.tsx
  src/shell/hooks/useSearchBlocksByKeyword.ts
  src/shell/views/SearchPage/SearchPage.tsx
Labels: bug
