Repository zesty-io/manager-ui, pull requests merged in 2025-03, with the labels that each got.

#3285 [Schema] Add autoFocus to delete confirmation input field
  src/apps/schema/src/app/components/DeleteModelDialogue.tsx
Labels: enhancement, ready

#3294 [Content] Prevent UI jank when creating or posting reply to a comment
  src/shell/components/Comment/CommentItem.tsx
  src/shell/components/Comment/CommentsList.tsx
  src/shell/components/Comment/InputField.tsx
Labels: enhancement, ready

#3274 [#3241] : One to one relationship field selection issue
  cypress/e2e/content/actions.spec.js
  cypress/e2e/content/comments.js
  cypress/e2e/content/content.spec.js
  cypress/e2e/content/item-list-table.spec.js
  cypress/e2e/media/folders.spec.js
  cypress/e2e/schema/models.spec.js
  package-lock.json
  package.json
  src/shell/components/RelationalFieldBase/ActiveItem/index.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/DialogHeader.tsx
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
  src/shell/components/RelationalFieldBase/index.tsx
Labels: enhancement

#3304 [Content] Remove frontend validation limits to one-to-many fields
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
Labels: bug, ready

#3282 [Content] Make sure newly-created field is always added at the end
  src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
Labels: bug, ready

#3293 [Content] Use tinymce's own placeholder implementation & autofocus input field on open
  public/vendors/tinymce/skins/ui/Zesty/content.css
  public/vendors/tinymce/skins/ui/Zesty/content.inline.css
  public/vendors/tinymce/skins/ui/Zesty/content.inline.min.css
  public/vendors/tinymce/skins/ui/Zesty/content.min.css
  src/shell/components/Comment/InputField.tsx
Labels: bug, ready

#3283 [Content] Update outline color on field focus
  src/apps/content-editor/src/app/components/FieldTypeMedia.tsx
Labels: enhancement, ready

#3324 [Content] VQA: Prevent dialog height shift
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
Labels: ready

#3318 [Block] Add a loading skeleton when capturing screenshot
  cypress/e2e/media/contentmodal.spec.js
  src/apps/content-editor/src/app/views/ItemEdit/components/BlockTabs.tsx
  src/shell/services/types.ts
  src/shell/store/content.js
Labels: enhancement, ready

#3234 [Content] Handle empty url string
  src/apps/content-editor/src/app/views/Analytics/components/AnalyticsPropertySelector.tsx
Labels: bug, ready

#3259 [Content] Handle error when fields fail to load
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx
Labels: bug, ready

#3327 [Global] Tab-specific pinning & overall tab enhancements
  cypress/e2e/media/contentmodal.spec.js
  src/shell/store/ui.ts
Labels: enhancement, ready

#3309 [#3269] Code: Drawer - UI Enhancements
  src/apps/code-editor/src/app/components/BottomDrawer/AuditTrail.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/FileCard.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/FileStatus.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/LinkedContent.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/LinkedSchema.tsx
  src/apps/code-editor/src/app/components/BottomDrawer/index.tsx
  src/apps/code-editor/src/app/components/Differ/Differ.js
  src/apps/code-editor/src/app/components/Differ/Differ.less
  src/apps/code-editor/src/app/components/Editor/Editor.js
  src/apps/code-editor/src/app/components/Editor/Editor.less
  src/apps/code-editor/src/app/components/SideBar/FileNav.tsx
  src/apps/code-editor/src/app/components/SideBar/index.tsx
  src/apps/code-editor/src/app/components/TopBar/DeleteDialog.tsx
  src/apps/code-editor/src/app/components/TopBar/DifferActions.tsx
  src/apps/code-editor/src/app/components/TopBar/EditorActions.tsx
  src/apps/code-editor/src/app/components/TopBar/index.tsx
  src/apps/code-editor/src/app/components/Workspace/Workspace.js
  src/apps/code-editor/src/app/components/Workspace/Workspace.less
  src/apps/code-editor/src/app/components/Workspace/components/FileViewer/FileViewer.js
  src/apps/code-editor/src/app/components/Workspace/components/FileViewer/FileViewer.less
  src/apps/code-editor/src/app/components/Workspace/components/FileViewer/index.js
  src/apps/code-editor/src/app/components/Workspace/index.js
  src/apps/code-editor/src/app/views/CodeEditor/CodeEditor.js
  src/shell/components/global-tabs/components/Tab.tsx
Labels: enhancement

#3348 [Schema] Add field modal enhancements
  src/apps/schema/src/app/components/configs.ts
Labels: enhancement, ready

#3339 [Content] Show year timestamp when version is from past year
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector.tsx
  src/utility/formatDate.ts
Labels: enhancement, ready

#3355 [Content] Prevent blank multiline comments
  src/shell/components/Comment/InputField.tsx
Labels: enhancement, ready
