Repository zesty-io/manager-ui, pull requests merged in 2025-05, with the labels that each got.

#3473 [#3034] Global: Cannot Access URL Screen Revamp
  public/images/restricted.png
  src/shell/components/AccessDenied.tsx
  src/shell/components/InvalidUrl.tsx
  src/shell/components/missing/index.js
  src/shell/components/missing/index.tsx
Labels: enhancement

#3465 [Content] No content item fields screen revamp
  public/images/fields-loading.png
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/Editor.less
  src/apps/content-editor/src/app/components/NoFields.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/schema/src/app/components/FieldList.tsx
  src/shell/store/types.ts
Labels: enhancement, ready

#3480 [Content] Update schedule publish modal header and button text
  src/shell/components/SchedulePublish/index.tsx
Labels: enhancement, ready

#3478 [Global] No instance permission revamp
  cypress/e2e/schema/activity-log.spec.js
  src/shell/components/load-instance/NoInstancePermission.tsx
  src/shell/components/load-instance/index.js
  src/shell/services/types.ts
  src/shell/store/types.ts
Labels: enhancement, ready

#3495 [#3458] Content: Multi Page Table - Pinned columns do not persist on refresh
  src/apps/content-editor/src/app/views/ItemList/ItemListTable.tsx
Labels: bug

#3489 [Content] Item locked modal revamp
  src/apps/content-editor/src/app/components/LockedItem/LockedItem.js
  src/apps/content-editor/src/app/components/LockedItem/LockedItem.less
  src/apps/content-editor/src/app/components/LockedItem/index.js
  src/apps/content-editor/src/app/components/LockedItem/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
Labels: enhancement, ready

#3490 [Maintenance] Updated github templates and added issue filing guideline on readme
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: ready, maintenance

#3460 [Content] Load content item skeleton loaders
  src/apps/active-preview/index.html
  src/apps/content-editor/src/app/components/ContentBreadcrumbs.tsx
  src/apps/content-editor/src/app/components/Editor/Editor.js
  src/apps/content-editor/src/app/components/Editor/FieldsLoader.tsx
  src/apps/content-editor/src/app/components/Editor/PreviewMode/PreviewMode.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/ContentInfo/index.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/ContentLinks/ContentLinks.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/ContentLinks/InstantUrl/InstantUrl.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/Unpublish/Unpublish.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetDeleteItem/WidgetDeleteItem.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetDraftHistory/WidgetDraftHistory.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetListed/WidgetListed.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetPublishHistory/WidgetPublishHistory.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetPurgeItem/WidgetPurgeItem.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetQuickShare/WidgetQuickShare.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WidgetQuickShare/WidgetQuickShare.less
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/WorkflowRequest/WorkflowRequest.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/ActionsDrawer.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/ActionsDrawer.less
  src/apps/content-editor/src/app/views/ItemEdit/Content/ActionsDrawer/index.js
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PreviewMenu.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PublishStatus.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
Labels: enhancement, ready

#3513 [Content] Prevent No Fields screen from briefly flashing
  src/apps/content-editor/src/app/views/ItemEdit/Content/Content.js
Labels: bug, ready

#3114 [Content] Workflow status
  cypress.config.js
  cypress/e2e/content/pages/ContentItemPage.js
  cypress/e2e/content/workflows.spec.js
  cypress/e2e/settings/workflows.spec.js
  cypress/support/commands.js
  public/images/restricted-image.svg
  src/apps/content-editor/src/app/views/ItemCreate/ItemCreate.tsx
  src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Actions.js
  src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/PublishStatus.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector/NoResults.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector/Row.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector/VersionItem.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/VersionSelector/index.tsx
  src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/index.tsx
  src/apps/schema/src/app/components/NoResults.tsx
  src/apps/settings/src/app/App.js
  src/apps/settings/src/app/components/Nav/SettingsNav.tsx
  src/apps/settings/src/app/views/User/Workflows/RestrictedPage.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/ActiveStatus.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/DeactivatedStatus.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/StatusLabel.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/forms-dialogs/DeactivationDialog.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/forms-dialogs/StatusLabelForm.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/forms-dialogs/index.tsx
  src/apps/settings/src/app/views/User/Workflows/authorized/index.tsx
  src/apps/settings/src/app/views/User/Workflows/constants.tsx
  src/apps/settings/src/app/views/User/Workflows/index.tsx
  src/shell/hooks/useResizeObserver.ts
  src/shell/services/instance.ts
  src/shell/services/types.ts
  src/shell/store/content.js
Labels: ready, feature

#3520 [Activity Log] Added proper formatting for workflow status updates
  src/apps/reports/src/app/views/ActivityLog/components/ActionTimelineItem/TimelineItem.js
Labels: enhancement, ready

#3518 [#2488] - Content: Item Has Been Deleted Revamp
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
  src/apps/content-editor/src/app/views/NotFound/NotFound.js
  src/apps/content-editor/src/app/views/NotFound/NotFound.less
  src/apps/content-editor/src/app/views/NotFound/index.js
  src/apps/content-editor/src/app/views/NotFound/index.tsx
Labels: enhancement

#3508 [#3498] Content: Publish Related Items checkbox re-checked after short delay
  src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js
Labels: bug

#3525 [Content] Create item modal UX updates
  cypress/e2e/content/navigation.spec.js
  src/shell/components/CreateContentItemDialog.tsx
Labels: enhancement, ready

#3542 [Content] Keep selected rows even when filtering in the relational field selector dialog
  cypress/e2e/content/content.spec.js
  src/shell/components/RelationalFieldBase/FieldSelectorDialog/index.tsx
Labels: bug, ready

#3423 [#3353]: Content: Multi Page Table - Skeleton Loading Screen
  src/apps/content-editor/src/app/views/ItemList/ItemListTable.tsx
  src/apps/content-editor/src/app/views/ItemList/Loader.tsx
  src/apps/content-editor/src/app/views/ItemList/index.tsx
  src/shell/components/DataGridSkeletonCell/index.tsx
Labels: enhancement

#3554 [Content] Show duplicate reference ID error message in line
  src/apps/schema/src/app/components/CreateModelDialogue.tsx
Labels: enhancement, ready
